name: SynVectorDB
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - streamlit=1.31.1
  - pandas=2.1.4
  - plotly=5.18.0
  - biopython=1.83
  - pytorch=2.2.0
  - numpy>=1.24.0
  - pip:
    - fastapi>=0.68.0
    - uvicorn>=0.15.0
    - pydantic>=1.8.0
    - sentence-transformers>=2.2.2
    - lancedb>=0.4.0
    - python-dotenv>=0.19.0
    - openai>=1.0.0
    - requests>=2.28.0
    - pymongo==4.6.1
